version: '2'
services:
  front:
    image: nginx:1.11.10
    ports:
      - "81:80"
    links:
      - "engine:engine"
    volumes:
      - ".:/home/docker:ro"
      - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
  engine:
    build: ./docker/engine/dev/
    volumes:
      - ".:/home/docker:rw"
      - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
      - "db:db"
    working_dir: "/home/docker"

  db:
    image: mysql:8.0.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=uscl
      - MYSQL_PASSWORD=uscl
      - MYSQL_DATABASE=uscl
    volumes:
      - my-datavolume:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '82:80'
volumes:
  my-datavolume: