services:
    admin.joueur:
            class: AppBundle\Admin\JoueurAdmin
            arguments: [~, AppBundle\Entity\Joueur, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Joueurs, group: "joueurs"}
            calls:
                - [ setKernel, ["@kernel"]]

    admin.club:
            class: AppBundle\Admin\ClubAdmin
            arguments: [~, AppBundle\Entity\Club, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Club, group: "club"}

    admin.dirigeant:
            class: AppBundle\Admin\DirigeantAdmin
            arguments: [~, AppBundle\Entity\Dirigeant, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Dirigeants, group: "club"}

    admin.carriere:
            class: AppBundle\Admin\CarriereAdmin
            arguments: [~, AppBundle\Entity\CarriereJoueur, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Carriere, group: "joueurs"}

    admin.utilisateurs:
            class: AppBundle\Admin\UserAdmin
            arguments: [~, AppBundle\Entity\User, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Utilisateurs, group: "utilisateurs"}

    admin.stats:
            class: AppBundle\Admin\StatsAdmin
            arguments: [~, ~, AppBundle:StatsAdmin]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Statistiques, group: "joueurs"}
            calls:
                - [ setTemplate, [add, SonataAdminBundle:Stats:stats.html.twig]]