app:
    resource: '@AppBundle/Controller/'
    type: annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

plans:
    path: /plans
    defaults:
        _controller: FrameworkBundle:Template:template
        template: default/plans.html.twig